---
- hosts: all

  vars_files:
    - defaults/main.yml
    - vars/main.yml

  vars:
    domain: test.dev

  vars_files:
    - defaults/main.yml
    - vars/main.yml

  roles:
    - role: bbatsche.Nginx
      passenger_app: yes

  tasks:
    - include: tasks/main.yml
