---
- name: Install NVM
  git:
    repo: https://github.com/creationix/nvm.git
    dest: "{{ nvm_root }}"
    version: "{{ nvm_version }}"
  become: yes

- name: Add NVM to Profile
  template: src=nvm.sh.j2 dest=/etc/profile.d/nvm.sh mode=755
  become: yes

- name: Create NVM Directories
  file: path={{ nvm_root }}/{{ item }} state=directory owner={{ ansible_ssh_user }} mode=0775
  with_items:
    - alias
    - bin
    - src
    - versions
  become: yes

- name: Add NVM Bash Completion
  lineinfile:
    dest: ~/.bashrc
    line: '[[ -r $NVM_DIR/bash_completion ]] && . $NVM_DIR/bash_completion'
    insertafter: EOF
    state: present

- name: Install Current Version
  shell: . /etc/profile.d/nvm.sh && nvm install {{ node_version }}
  args:
    creates: "{{ nvm_root }}/versions/node/{{ node_version }}"

- name: Copy app.js Stub
  template: src=app.js.j2 dest={{ http_root }}/{{ domain }}/app.js
  when: copy_appjs
  notify: Restart Passenger App
