---
- hosts: all

  vars_files:
    - ../../vars/main.yml
    - ../../defaults/main.yml
    
  vars:
    site_type: node
    domain: node-test.dev
    
  roles:
    - bbatsche.Nginx
      
  tasks:
    - include: ../../tasks/main.yml
